// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEkDIpLXHgX8fRHPSMP6EbrfcjGgjcshw',
    appId: '1:285615288336:web:3ff23d349783661cee9a95',
    messagingSenderId: '285615288336',
    projectId: 'money-splitter-94244',
    authDomain: 'money-splitter-94244.firebaseapp.com',
    storageBucket: 'money-splitter-94244.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVfiNCVH2RDdT5x3jqglfRuP9tGjfYko',
    appId: '1:285615288336:android:c94f7fa9388c69a2ee9a95',
    messagingSenderId: '285615288336',
    projectId: 'money-splitter-94244',
    storageBucket: 'money-splitter-94244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZRSFS_KnRrgqSfV50JhvP9bcGj8Emr1k',
    appId: '1:285615288336:ios:4bd1fccfa3ea1dd6ee9a95',
    messagingSenderId: '285615288336',
    projectId: 'money-splitter-94244',
    storageBucket: 'money-splitter-94244.appspot.com',
    iosClientId: '285615288336-20r9hshasmfu6i716qtahuq5asqjngc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneySplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZRSFS_KnRrgqSfV50JhvP9bcGj8Emr1k',
    appId: '1:285615288336:ios:a915d9701857798dee9a95',
    messagingSenderId: '285615288336',
    projectId: 'money-splitter-94244',
    storageBucket: 'money-splitter-94244.appspot.com',
    iosClientId: '285615288336-ihesjaqekbp4m7in7ro1indsr1sv23np.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneySplitter.RunnerTests',
  );
}
